### ISSUE TITLE
推荐游戏内嵌测试

### ISSUE THREAD

**Issue by a6070160701** [HIllya51/TextEmbedder#1]
1.SHRIFT
这个我是看到大家对于剧情评价很高
所以我目前正在推的
个人颇喜欢魔物娘
但那种只有耳朵或尾巴的魔物娘根本太常见了
所以对于这类有[大幅度]魔物化的女怪特别有好感
而且里面的逆推动画也相当戳我的性癖.
如果能内嵌享受剧情
应该会相当舒适
(目前使用luna的话.会有各种需要去除的数字和符号.
在游戏进行中.因为有很多其他日文资讯.所以也常常干扰到翻译效果)

2.空蝉コミュニクション
我推这个的原因是因为.
我挺喜欢里面的点阵H动画的.
虽然共通的部分可能会常看到腻.
不过每个人都或多或少有一些独特的play会享用到.
对于想享受新鲜的H表现方式的人.
这款相当适合.
至于剧情部分.
每个人都有各自的起承转合.
虽说不上十分优秀.
但也是很不错的小品.

**Comment by HIllya51** [comment]
1用哪个版本的，6.03吗

**Comment by a6070160701** [comment]
> 1用哪个版本的，6.03吗

我自己是在其他地方用6.30版本的
实际上应该要用最新版本的才对
就我所知道
最新版本应该是8.07
我可能要花时间找一下看看有没有再传给你

**Comment by a6070160701** [comment]
> 1用哪个版本的，6.03吗

我找到载点了
在论坛PM给你了
如果你不能下或速度太慢再跟我说看要换哪个空间

**Comment by HIllya51** [comment]
ok了

**Comment by a6070160701** [comment]
> ok了

嗯嗯 再寄一封DLC给你

**Comment by a6070160701** [comment]
> ok了

我刚刚试了一下
原档把save资料夹和PublicData.rvdata2这个档案删掉
应该就可以回到初始状态了

**Comment by HIllya51** [comment]
空蝉这个b游戏怎么跳过&保存啊 我吐了

**Comment by HIllya51** [comment]
另外换个网盘，这网盘我下了两次下到2/3没速度了

**Comment by a6070160701** [comment]
> 空蝉这个b游戏怎么跳过&保存啊 我吐了
开场那边没办法
我自己是在某些没办法跳过的过场时会开CE加速
不过最多也只能到3倍速
CTRL有加速对话的功能

这边丢给你一个跳过开头的存档
可以移动后按C可以存档
[Save.zip](https://github.com/HIllya51/TextEmbedder/files/10755591/Save.zip)

**Comment by a6070160701** [comment]
> 另外换个网盘，这网盘我下了两次下到2/3没速度了

GD上傳中

**Comment by a6070160701** [comment]
uploading...

**Comment by a6070160701** [comment]
已PM

**Comment by a6070160701** [comment]
对了
顺便问个问题
内嵌也会因为游戏版本的不同而导致失效是吗?

**Comment by HIllya51** [comment]
看运气

**Comment by HIllya51** [comment]
测试1本来就可以内嵌。
2实在太过恶心，启动一下等半天，没心情搞了，放弃~

**Comment by a6070160701** [comment]
嗯嗯
OK
谢谢你的内嵌

至于2某些过场是比较烦没错
途中移到别的视窗也会自动暂停
辛苦你了

**Comment by a6070160701** [comment]
关于1
刚刚用了最新版的luna
我点内嵌之后
选择游戏进程之后
然后就进入一小段读取时间
之后luna就自动关闭了
请问这是我自身的问题吗?
P.S.我是在sandboxie执行的

**Comment by HIllya51** [comment]
你都说了是在sandboxie执行的了。

**Comment by a6070160701** [comment]
好吧
看来只能拉出来试了
因为sandboxie会有隔离某些档案产生或移动的效果
简单来说我想要有些小小的保护就是哩
不过看来它大概跟内嵌这功能有点冲突
其他功能是都可以正常在sandboxie内执行

**Comment by a6070160701** [comment]
我后来发现不管有没有开sandboxie
都是一样
可能不是sandboxie的问题
选择内嵌的游戏后
按OK后就会读取一阵子
然后就会自动结束程序
已经下最新版了
也删除资料夹整个重新开1次luna了
都是一样的结果
不知道是哪边的问题

之后我再研究研究吧
先来睡哩
